### ISSUE TITLE
Can you share some clue about the way to find out the magic number?

### ISSUE THREAD

**Issue by bitxel** [sillyousu/goid#3]
it's an awesome library! thanks for the nice work, can you share a little bit about how do you find out the magic number?

**Comment by patricksuo** [comment]
You can copy the struct `g` from runtime and find out the offset of `goid` with `unsafe.Offset`
https://play.golang.org/p/XPL--Lcl24n

Or you can disassemble arbitrary go program and see how does go runtime access the `goid`.
https://github.com/golang/go/blob/99e6e482f4f03d80c7dcf1c33b4f49f349d4b3b6/src/runtime/proc.go#L1671

```
  42d494:       b8 01 00 00 00          mov    $0x1,%eax
  42d499:       48 8d 15 20 d8 1a 00    lea    0x1ad820(%rip),%rdx        # 5dacc0 <runtime.sched>
  42d4a0:       f0 48 0f c1 02          lock xadd %rax,(%rdx)
  42d4a5:       48 ff c0                inc    %rax
  42d4a8:       48 89 81 98 00 00 00    mov    %rax,0x98(%rcx)
  42d4af:       48 89 0c 24             mov    %rcx,(%rsp)     
  42d4b3:       e8 d8 d3 ff ff          callq  42a890 <runtime.allgadd>
```
